---
sidebar: sidebar 
permalink: alerts-faq.html 
keywords: alerts faq, alerts frequently asked questions, bluexp, bluexp alert 
summary: 이 NetApp 알림 FAQ는 질문에 대한 빠른 답변을 찾는 데 도움이 될 수 있습니다. 
---
= NetApp 알림에 대한 자주 묻는 질문
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp 알림에 대한 질문에 대한 빠른 답변을 찾고 있다면 이 FAQ가 도움이 될 수 있습니다.



== NetApp 알림에 액세스

* NetApp 알림 URL은 무엇입니까?*  브라우저에서 URL을 입력하세요. https://console.netapp.com/["https://console.netapp.com/"^] NetApp 콘솔에 액세스합니다.

* NetApp 알림을 사용하려면 라이선스가 필요합니까?*

NetApp 알림을 사용하려면 NetApp ONTAP 9.10 이상 라이선스가 필요합니다.  라이센스를 NetApp 콘솔 디지털 지갑에 입력할 필요가 없습니다.

NetApp 알림에는 평가판 라이선스가 필요하지 않습니다.

* NetApp 알림을 어떻게 활성화하나요?*  NetApp 알림에는 어떠한 활성화도 필요하지 않습니다.  알림 옵션은 NetApp 콘솔 왼쪽 탐색에서 자동으로 활성화됩니다.

시작하려면 콘솔 에이전트를 사용하면 NetApp 알림에 적합한 기능이 포함됩니다.

** NetApp 알림은 표준, 제한 및 비공개 모드에서 사용할 수 있나요?**  NetApp 알림은 NetApp 콘솔 표준(공개)에서만 배포할 수 있습니다.

모든 NetApp 콘솔 서비스에서 이러한 모드에 대한 설명은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["NetApp 콘솔 배포 모드"^] .

**접근 권한은 어떻게 처리되나요?**  NetApp 콘솔 조직 관리자만 NetApp 알림을 시작하고 워크로드를 검색할 수 있습니다(이는 리소스 사용에 대한 커밋을 포함하기 때문).

알림은 NetApp 콘솔 조직 내 클러스터 리소스에 대한 액세스 권한에 따라 로그인한 사용자에게 표시됩니다.



== 알림 보기

**알림을 받기까지 얼마나 기다려야 하나요?**

최초 발견까지 최대 15분을 기다리세요. 그 후 알림이 나타날 때까지 최대 5분을 기다리세요.  이는 경보마다 다릅니다.

**콘솔 에이전트 없이 직접 모드를 사용하여 ONTAP 에 대한 알림을 볼 수 없는 이유는 무엇입니까?*

NetApp 알림은 온프레미스 표준 콘솔 에이전트를 통해서만 사용할 수 있습니다.  직접 모드를 사용하면 클러스터를 모니터링하지 않고 경고도 표시하지 않습니다.

**일부 알림이 알림 목록 페이지에서 사라지는 이유는 무엇인가요?**

알림 기능은 일부 알림을 활성 상태로 유지하고 카운터 조건이 충족되거나 일정 시간이 지나면 알림을 닫습니다.  이는 경보마다 다릅니다.

모든 알림을 보려면 상태 열 필터를 선택하고 닫힘 옵션을 선택하세요.



== 정보 표시

**어떤 기기에 가장 적합한 해상도가 있나요?**  NetApp 알림에 권장되는 장치 해상도는 1920x1080 이상입니다.

**어떤 브라우저를 사용해야 하나요?**  모든 최신 브라우저에서 작동합니다.
