---
sidebar: sidebar 
permalink: concept-alerts.html 
keywords: netapp, ontap, alert, capacity, performance, availability, security, protection, bluexp, NetApp Console alerts 
summary: NetApp ONTAP 환경에서 용량, 성능, 가용성 및 보안과 관련된 문제나 잠재적 위험을 확인하세요.  ONTAP 시스템 관리자를 사용하면 자세한 내용을 살펴볼 수 있습니다. 
---
= ONTAP 알림에 대해 알아보세요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 콘솔을 사용하여 NetApp 온프레미스 ONTAP 시스템의 문제나 잠재적 위험을 확인하세요.  ONTAP 시스템 관리자를 사용하면 자세한 내용을 살펴볼 수 있습니다.



== NetApp 콘솔

NetApp 콘솔에서 ONTAP 알림을 확인하세요.

NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지 및 데이터 서비스를 중앙에서 관리할 수 있는 기능을 제공합니다. NetApp 데이터 서비스에 액세스하고 사용하려면 콘솔이 필요합니다. 관리 인터페이스로서, 하나의 인터페이스에서 여러 스토리지 리소스를 관리할 수 있습니다. 콘솔 관리자는 기업 내 모든 시스템의 저장소와 서비스에 대한 액세스를 제어할 수 있습니다.

NetApp 콘솔을 사용하려면 라이선스나 구독이 필요하지 않으며, 스토리지 시스템이나 NetApp 데이터 서비스에 대한 연결을 보장하기 위해 클라우드에 콘솔 에이전트를 배포해야 할 때만 요금이 부과됩니다. 그러나 콘솔에서 액세스할 수 있는 일부 NetApp 데이터 서비스는 라이선스 기반이거나 구독 기반입니다.

자세히 알아보세요 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp 콘솔"] .



== ONTAP 알림으로 할 수 있는 일

ONTAP 알림을 확인하여 ONTAP 스토리지 시스템의 위험이나 잠재적 위험에 대한 정보를 얻으세요.  EMS가 아닌 알림과 EMS 알림을 볼 수 있습니다.  다음의 심각도와 영향 영역에 대한 정보를 확인할 수 있습니다.

* *심각도*: 중요, 경고, 정보
* *영향 영역*: 용량, 성능, 보호, 가용성, 보안, 구성



TIP: NetApp 콘솔 UI의 오른쪽 상단에 있는 알림 옵션은 NetApp 콘솔이 수행하는 작업 상태를 모니터링하여 해결해야 할 문제를 식별하는 데 도움을 줍니다.  이러한 알림을 이메일로 받을 수 있습니다.  알림 옵션에는 ONTAP 알림이 ​​포함되지 않습니다.



== ONTAP 알림 모니터링의 이점

ONTAP 알림을 모니터링하면 다음과 같은 이점이 있습니다.

* 클러스터 전체의 ONTAP 스토리지에 대한 알림을 받으세요.
* 다른 서비스에 사용하는 것과 동일한 NetApp 콘솔 UI에서 알림을 확인하세요.
* ONTAP 클러스터에 대한 알림을 자세히 살펴보세요. NetApp 콘솔에서 시작하여 ONTAP 시스템 관리자에서 세부 정보를 확인하세요.




== 비용

NetApp ONTAP 라이선스를 사용하면 ONTAP 알림을 볼 수 있습니다.



== 라이센스

ONTAP 알림을 보려면 NetApp ONTAP 9.10 이상 라이선스가 필요합니다.

평가판 라이센스가 필요하지 않습니다.

ONTAP 알림은 NetApp 콘솔 표준(공개) 모드에서만 볼 수 있습니다.



== ONTAP 알림 작동 방식

ONTAP 알림은 NetApp 콘솔의 핵심 구성 요소입니다.  ONTAP 알림은 ONTAP 클러스터를 모니터링하고 ONTAP 에서 알림 데이터를 수신합니다.

ONTAP 알림은 NetApp Console SaaS 환경에서만 사용할 수 있습니다.  로컬 콘솔 에이전트 UI에서는 사용할 수 없습니다.



== 지원되는 시스템 및 데이터 소스

ONTAP 알림을 사용하여 다음 시스템 및 데이터 소스의 문제를 확인하세요.

*지원 시스템*

온프레미스 ONTAP NAS 또는 SAN 시스템이 지원됩니다.

현재 Cloud Volumes ONTAP 시스템은 지원되지 않습니다.

*지원되는 데이터 소스*

ONTAP 에서 발생하는 특정 이벤트에 대한 알림을 확인합니다.  이는 EMS와 지표 기반 알림의 조합입니다.
